# Generated by Django 5.1.4 on 2024-12-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.IntegerField()),
                ("timestamp", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField()),
                ("heading", models.FloatField()),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.IntegerField()),
                ("frame_start", models.IntegerField()),
                ("frame_end", models.IntegerField()),
                ("start_point", models.JSONField()),
                ("end_point", models.JSONField()),
                ("center", models.JSONField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("timestamp_start", models.FloatField()),
                ("timestamp_end", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="videos/")),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("start_latitude", models.FloatField()),
                ("start_longitude", models.FloatField()),
                ("end_latitude", models.FloatField()),
                ("end_longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.IntegerField()),
                ("bbox", models.JSONField()),
                ("confidence", models.FloatField()),
                ("world_speed", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="videos.frame",
                    ),
                ),
                (
                    "tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="videos.tracking",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tracking",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="videos.video",
            ),
        ),
        migrations.AddField(
            model_name="frame",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frames",
                to="videos.video",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tracking",
            unique_together={("video", "track_id")},
        ),
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.IntegerField()),
                ("timestamp", models.FloatField()),
                ("intersection_point", models.JSONField()),
                (
                    "intersection_point_type",
                    models.CharField(default="center", max_length=50),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("time_difference", models.FloatField()),
                ("distance", models.FloatField(blank=True, null=True)),
                (
                    "track1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track1_intersections",
                        to="videos.tracking",
                    ),
                ),
                (
                    "track2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track2_intersections",
                        to="videos.tracking",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intersections",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["video", "track1", "track2"],
                        name="videos_inte_video_i_d66d1f_idx",
                    )
                ],
            },
        ),
    ]
